### ISSUE TITLE
Parameters to split - daywise at night

### ISSUE THREAD

**Issue by rokdd** [hrehfeld/split-gpx-track#2]
Hello

thanks for your wonderful script, it is a very good starting point for I want to achieve: Splitting gpx file by day (normally around 4am at night), so each photo session has its own file. I guess I sleep every day your parameters should find out easily when are the breaks. But I have some trouble to understand them:

- pauses need to be at least this long
pause_min_timedelta = timedelta(hours=1.5)
(I assume this fine for me)
- pauses cant be faster than
pause_max_velocity = 2
(how can a pause have a velocity?)
- time gap of this length forces start of a new track
route_max_timedelta = timedelta(hours=4)
(so this means each track is maximum 4h long?)

Thanks for your help (and your work)!

**Comment by hrehfeld** [comment]
> * pauses need to be at least this long
>   pause_min_timedelta = timedelta(hours=1.5)
>   (I assume this fine for me)
> * pauses cant be faster than
>   pause_max_velocity = 2
>   (how can a pause have a velocity?)

``` python
                if route and moved:
                    dt = t - route[-1][1]
                    assert dt.seconds >= 0
                    velocity = vel(route_d, dt)
                    # last point was long ago, and we didnt travel during this time
                    if (
                        dt > pause_min_timedelta and velocity < pause_max_velocity
                    ) or dt > route_max_timedelta:
                        pause_start = route[-1]
```
Velocity is checked because e.g. in a train you often don't have gps at all, but you move alot. This basically detects a pause if you lose gps and don't move fast in the mean time.

> * time gap of this length forces start of a new track
>   route_max_timedelta = timedelta(hours=4)
>   (so this means each track is maximum 4h long?)
see above.

If you lose gps for more than 4 hours, we split here regardless of how far you moved in the meantime.
